"""DEVELOPMENT DATA ONLY - these are NOT real job postings.

Every job produced from this file is flagged ``is_mock=True`` all the way to the
API response and is rendered with a "DEMO" badge in the UI. It exists so the app
is fully demonstrable when a real source is unreachable or unconfigured.

Delete this module (and ``MockJobCollector``) once every collector you care about
is live, or simply leave ``DEMO_MODE=false`` in .env.
"""

from __future__ import annotations

from typing import Any

# fmt: off
MOCK_JOBS: list[dict[str, Any]] = [
    {"id": "m001", "title": "베트남어 가능 해외영업 담당자 모집", "company": "ABC 주식회사",
     "location": "서울 강남구", "salary": "연봉 3,500만원~", "employment_type": "정규직",
     "experience": "경력무관", "days_ago": 0,
     "description": "베트남 현지 바이어 응대 및 수출입 업무. 베트남어 회화 가능자 우대.",
     "tags": ["베트남어", "외국인", "영업", "해외영업"]},
    {"id": "m002", "title": "베트남어 통역원 (생산관리팀)", "company": "대한정밀공업",
     "location": "경기 화성시", "salary": "연봉 3,200만원", "employment_type": "정규직",
     "experience": "신입", "days_ago": 1,
     "description": "생산 현장 베트남 근로자 통역 및 노무 지원. 한국어 TOPIK 5급 이상.",
     "tags": ["베트남어", "통역", "외국인", "생산"]},
    {"id": "m003", "title": "외국인 근로자 관리 담당 (베트남어/한국어)", "company": "한빛인력개발",
     "location": "인천 남동구", "salary": "월급 280만원", "employment_type": "계약직",
     "experience": "경력", "days_ago": 2,
     "description": "외국인 근로자 입사/체류 서류 관리, 통역 지원 업무.",
     "tags": ["베트남어", "외국인", "통역", "인사"]},
    {"id": "m004", "title": "베트남어 통역 및 무역사무 채용", "company": "미래통상",
     "location": "부산 해운대구", "salary": "연봉 3,000만원~3,800만원", "employment_type": "정규직",
     "experience": "경력무관", "days_ago": 3,
     "description": "베트남 거래처 이메일/전화 통역, 무역 서류 작성.",
     "tags": ["베트남어", "통역", "무역"]},
    {"id": "m005", "title": "[외국인 채용] 물류센터 상하차 (비자 무관)", "company": "코리아로지스",
     "location": "경기 김포시", "salary": "시급 12,000원", "employment_type": "아르바이트",
     "experience": "경력무관", "days_ago": 0,
     "description": "외국인 지원 가능. 주 5일 근무, 기숙사 제공.",
     "tags": ["외국인", "물류", "알바"]},
    {"id": "m006", "title": "베트남어 강사 모집 (주 3회)", "company": "글로벌에듀센터",
     "location": "서울 마포구", "salary": "시급 35,000원", "employment_type": "프리랜서",
     "experience": "경력", "days_ago": 4,
     "description": "성인 대상 베트남어 회화 강의. 원어민 또는 상급자.",
     "tags": ["베트남어", "강사", "교육"]},
    {"id": "m007", "title": "외국인 전용 식품제조 생산직 사원", "company": "우리푸드",
     "location": "충남 천안시", "salary": "월급 260만원", "employment_type": "정규직",
     "experience": "신입", "days_ago": 5,
     "description": "식품 포장 라인 근무. E-9, F-2, F-4 비자 소지자 지원 가능.",
     "tags": ["외국인", "생산", "제조"]},
    {"id": "m008", "title": "베트남어/영어 통역 코디네이터", "company": "서울메디컬투어",
     "location": "서울 서초구", "salary": "연봉 3,600만원", "employment_type": "정규직",
     "experience": "경력", "days_ago": 6,
     "description": "외국인 환자 진료 동행 통역 및 상담.",
     "tags": ["베트남어", "통역", "의료", "외국인"]},
    {"id": "m009", "title": "해외사업부 베트남 주재원 (신입 가능)", "company": "신한전자",
     "location": "서울 영등포구", "salary": "연봉 4,200만원", "employment_type": "정규직",
     "experience": "경력무관", "days_ago": 7,
     "description": "베트남 하노이 법인 파견 예정. 베트남어 또는 영어 능통자.",
     "tags": ["베트남어", "해외", "주재원"]},
    {"id": "m010", "title": "외국인 상담원 (베트남어 CS)", "company": "케이티씨에스",
     "location": "대전 유성구", "salary": "월급 250만원", "employment_type": "계약직",
     "experience": "신입", "days_ago": 8,
     "description": "베트남어 인바운드 고객 상담. 교육 후 배치.",
     "tags": ["베트남어", "상담", "외국인", "CS"]},
    {"id": "m011", "title": "통역 아르바이트 (베트남어, 단기)", "company": "이벤트코리아",
     "location": "서울 송파구", "salary": "일급 150,000원", "employment_type": "아르바이트",
     "experience": "경력무관", "days_ago": 1,
     "description": "전시회 부스 통역 3일 단기 근무.",
     "tags": ["베트남어", "통역", "알바", "단기"]},
    {"id": "m012", "title": "베트남어 번역가 (재택 프리랜서)", "company": "트랜스랩",
     "location": "전국", "salary": "건당 협의", "employment_type": "프리랜서",
     "experience": "경력", "days_ago": 9,
     "description": "기술 문서 한-베 번역. 재택 근무 가능.",
     "tags": ["베트남어", "번역", "재택"]},
    {"id": "m013", "title": "외국인 근로자 기숙사 관리 인턴", "company": "성진산업",
     "location": "경기 안산시", "salary": "월급 220만원", "employment_type": "인턴",
     "experience": "신입", "days_ago": 10,
     "description": "6개월 인턴 후 정규직 전환 가능. 외국인 소통 업무 다수.",
     "tags": ["외국인", "인턴", "관리"]},
    {"id": "m014", "title": "베트남어 가능 구매팀 사원", "company": "동아무역",
     "location": "인천 연수구", "salary": "연봉 3,300만원", "employment_type": "정규직",
     "experience": "경력", "days_ago": 11,
     "description": "베트남 공장 자재 구매 및 발주 관리.",
     "tags": ["베트남어", "구매", "무역"]},
    {"id": "m015", "title": "다문화가족 지원센터 베트남어 상담사", "company": "서울다문화지원센터",
     "location": "서울 구로구", "salary": "월급 240만원", "employment_type": "계약직",
     "experience": "경력무관", "days_ago": 12,
     "description": "결혼이주여성 대상 통번역 및 생활 상담.",
     "tags": ["베트남어", "통역", "상담", "다문화"]},
    {"id": "m016", "title": "외국인 채용 - 자동차 부품 조립", "company": "한국오토파츠",
     "location": "경남 창원시", "salary": "월급 290만원", "employment_type": "정규직",
     "experience": "경력무관", "days_ago": 13,
     "description": "주야 2교대. 외국인 근로자 다수 재직 중.",
     "tags": ["외국인", "생산", "제조"]},
    {"id": "m017", "title": "베트남어 SNS 마케터", "company": "플러스미디어",
     "location": "서울 강서구", "salary": "연봉 3,400만원", "employment_type": "정규직",
     "experience": "신입", "days_ago": 14,
     "description": "베트남 시장 SNS 콘텐츠 기획 및 운영.",
     "tags": ["베트남어", "마케팅", "SNS"]},
    {"id": "m018", "title": "통역병행 품질관리(QC) 담당자", "company": "정우테크",
     "location": "경기 평택시", "salary": "연봉 3,700만원", "employment_type": "정규직",
     "experience": "경력", "days_ago": 15,
     "description": "베트남어 통역 가능한 QC 인력 채용.",
     "tags": ["베트남어", "통역", "품질", "QC"]},
    {"id": "m019", "title": "외국인 유학생 아르바이트 (카페)", "company": "카페드림",
     "location": "부산 부산진구", "salary": "시급 11,000원", "employment_type": "아르바이트",
     "experience": "경력무관", "days_ago": 2,
     "description": "D-2 비자 시간제 취업허가 소지자 지원 가능.",
     "tags": ["외국인", "알바", "카페", "유학생"]},
    {"id": "m020", "title": "베트남 현지 법인 회계 담당", "company": "하노이무역",
     "location": "해외 베트남 하노이", "salary": "연봉 4,000만원", "employment_type": "정규직",
     "experience": "경력", "days_ago": 16,
     "description": "베트남 하노이 근무. 베트남어 또는 영어 필수.",
     "tags": ["베트남어", "회계", "해외"]},
    {"id": "m021", "title": "외국인 근로자 안전교육 강사", "company": "안전보건교육원",
     "location": "대구 달서구", "salary": "일급 200,000원", "employment_type": "프리랜서",
     "experience": "경력", "days_ago": 17,
     "description": "베트남어/캄보디아어 통역 동반 안전교육 진행.",
     "tags": ["외국인", "통역", "교육", "안전"]},
    {"id": "m022", "title": "베트남어 콜센터 팀장", "company": "글로벌콜",
     "location": "광주 서구", "salary": "연봉 4,500만원", "employment_type": "정규직",
     "experience": "경력", "days_ago": 18,
     "description": "베트남어 상담팀 운영 및 인력 관리.",
     "tags": ["베트남어", "상담", "관리자"]},
    {"id": "m023", "title": "[인턴] 해외마케팅 (베트남 시장)", "company": "케이뷰티글로벌",
     "location": "서울 성동구", "salary": "월급 230만원", "employment_type": "인턴",
     "experience": "신입", "days_ago": 19,
     "description": "화장품 베트남 수출 마케팅 인턴 6개월.",
     "tags": ["베트남어", "마케팅", "인턴", "해외"]},
    {"id": "m024", "title": "외국인 전문 부동산 중개보조원", "company": "글로벌홈즈",
     "location": "경기 수원시", "salary": "월급 270만원", "employment_type": "계약직",
     "experience": "경력무관", "days_ago": 20,
     "description": "외국인 대상 원룸/오피스텔 안내. 통역 가능자 우대.",
     "tags": ["외국인", "통역", "부동산"]},
    {"id": "m025", "title": "베트남어 게임 현지화(LQA) 담당", "company": "넥스트게임즈",
     "location": "서울 강남구", "salary": "연봉 3,900만원", "employment_type": "정규직",
     "experience": "경력무관", "days_ago": 21,
     "description": "모바일 게임 베트남어 번역 검수 및 현지화.",
     "tags": ["베트남어", "번역", "게임", "IT"]},
    {"id": "m026", "title": "외국인 근로자 채용 담당 (HR)", "company": "제일인력",
     "location": "울산 남구", "salary": "연봉 3,100만원", "employment_type": "정규직",
     "experience": "신입", "days_ago": 22,
     "description": "고용허가제(EPS) 외국인 근로자 채용 실무.",
     "tags": ["외국인", "인사", "채용"]},
    {"id": "m027", "title": "베트남어 무역사무 아르바이트", "company": "성일교역",
     "location": "인천 중구", "salary": "시급 13,000원", "employment_type": "아르바이트",
     "experience": "경력무관", "days_ago": 3,
     "description": "주 3일 근무. 서류 정리 및 간단한 통역.",
     "tags": ["베트남어", "무역", "알바", "통역"]},
    {"id": "m028", "title": "외국인 대상 한국어 강사", "company": "세종한국어학당",
     "location": "서울 종로구", "salary": "시급 30,000원", "employment_type": "계약직",
     "experience": "경력", "days_ago": 23,
     "description": "베트남/네팔 학습자 대상 한국어 수업. 한국어교원 2급 필수.",
     "tags": ["외국인", "강사", "한국어", "교육"]},
    {"id": "m029", "title": "베트남어 통역 (건설현장)", "company": "대성건설",
     "location": "전남 여수시", "salary": "월급 320만원", "employment_type": "계약직",
     "experience": "경력", "days_ago": 24,
     "description": "플랜트 현장 베트남 근로자 통역 및 안전관리 보조.",
     "tags": ["베트남어", "통역", "건설"]},
    {"id": "m030", "title": "외국인 채용 - 수산물 가공", "company": "동해수산",
     "location": "강원 강릉시", "salary": "월급 280만원", "employment_type": "정규직",
     "experience": "경력무관", "days_ago": 25,
     "description": "기숙사 및 식사 제공. 외국인 근로자 환영.",
     "tags": ["외국인", "생산", "수산"]},
    {"id": "m031", "title": "베트남어 능통 개발자 (백엔드)", "company": "테크브릿지",
     "location": "서울 강남구", "salary": "연봉 5,500만원", "employment_type": "정규직",
     "experience": "경력", "days_ago": 26,
     "description": "베트남 오프쇼어 개발팀과 협업. Python/FastAPI 경험 우대.",
     "tags": ["베트남어", "개발", "IT", "백엔드"]},
    {"id": "m032", "title": "외국인 근로자 통역 지원 (야간)", "company": "삼정산업",
     "location": "경기 시흥시", "salary": "월급 300만원", "employment_type": "계약직",
     "experience": "경력무관", "days_ago": 27,
     "description": "야간 근무조 통역 지원. 베트남어 또는 태국어.",
     "tags": ["외국인", "통역", "야간"]},
    {"id": "m033", "title": "베트남어 여행 상품 기획자", "company": "하나투어파트너",
     "location": "서울 중구", "salary": "연봉 3,450만원", "employment_type": "정규직",
     "experience": "신입", "days_ago": 28,
     "description": "베트남 패키지 상품 기획 및 현지 커뮤니케이션.",
     "tags": ["베트남어", "여행", "기획"]},
    {"id": "m034", "title": "외국인 전용 편의점 야간 알바", "company": "씨유가맹점",
     "location": "대전 서구", "salary": "시급 11,500원", "employment_type": "아르바이트",
     "experience": "경력무관", "days_ago": 4,
     "description": "야간 22시~08시. 외국인 지원 가능(비자 확인).",
     "tags": ["외국인", "알바", "편의점"]},
    {"id": "m035", "title": "베트남어 통역 인턴 (무역회사)", "company": "한성인터내셔널",
     "location": "부산 중구", "salary": "월급 210만원", "employment_type": "인턴",
     "experience": "신입", "days_ago": 29,
     "description": "3개월 인턴. 통역 및 수출 서류 보조.",
     "tags": ["베트남어", "통역", "인턴", "무역"]},
    {"id": "m036", "title": "외국인 근로자 대상 보험 설계사", "company": "굿라이프금융",
     "location": "전국", "salary": "회사내규에 따름", "employment_type": "프리랜서",
     "experience": "경력무관", "days_ago": 30,
     "description": "외국인 커뮤니티 대상 보험 상담. 통역 가능자 우대.",
     "tags": ["외국인", "보험", "영업", "통역"]},
]
# fmt: on
